version: '2.2'

services:
  controller:
    image: dtr.corp.appdynamics.com/appdynamics/enterprise-console:latest
    container_name: controller
    ports:
    - "8080:8080"
    - "9080:9080"
    - "9200:9200"
  machine:
    container_name: machine
    environment:
    - APPDYNAMICS_AGENT_ACCOUNT_NAME=customer1
    - APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY=SJ5b2m7d1$$354
    - APPDYNAMICS_CONTROLLER_HOST_NAME=controller
    - APPDYNAMICS_CONTROLLER_SSL_ENABLED=false
    - APPDYNAMICS_CONTROLLER_PORT=8080
    - EVENTS_SERVICE_HOST=controller
    - MACHINE_AGENT_PROPERTIES=-Dappdynamics.sim.enabled=true -Dappdynamics.docker.enabled=false -Dappdynamics.agent.uniqueHostId=nginxTest -Dappdynamics.controller.port=8080
    build:
      context: .
      dockerfile: Dockerfile_MA
    volumes:
    - /:/hostroot:ro
    - /var/run/docker.sock:/var/run/docker.sock
    - /opt/buildAgent/work/machine-agent-logs:/opt/appdynamics/machine-agent/logs